use super::*;

mod when_struct_complex_method_regular_async;
mod when_struct_generic_method_generic_async;
mod when_struct_generic_method_regular_async;
mod when_struct_regular_method_generic_async;
mod when_struct_regular_method_regular_async;
